version: "3"
services:

  flask:
    image: smartlab/flask
    env_file:
        - .env.development
    volumes:
        - ./app:/app
        - ./reports:/tmp
    command: 
        - uwsgi
    networks:
      - backend

  nginx:
    image: smartlab/nginx
    ports:
      - "5000:80"
    volumes:
      - ./nginx.vh.default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - frontend
      - backend
    depends_on:
      - flask

networks:
  frontend:
  backend:

volumes:
  flask-lib:
  flask-usr-lib:
